name: example

on:
  pull_request:
    types: [opened]

jobs:
  example:
    name: Release management comment
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Comment on PR
        uses: tiwanari/list-merged-pull-requests@hotfix/comment
        with:
          token: ${{ github.token }}
